# Generated by Django 4.0.3 on 2022-05-25 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direct_Pos',
            new_name='UserDirect',
        ),
        migrations.RenameModel(
            old_name='Prof_Pos',
            new_name='UserProf',
        ),
    ]
