# Generated by Django 4.0.3 on 2022-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
