# Generated by Django 4.0.3 on 2022-05-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0005_rename_direct_id_profile_direct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='direct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct', to='professions.direction'),
        ),
        migrations.AlterField(
            model_name='userdirect',
            name='direct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_direct', to='professions.direction'),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to='professions.profile'),
        ),
    ]
