# Generated by Django 4.0.3 on 2022-05-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0006_alter_profile_direct_alter_userdirect_direct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdirect',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprof',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
